services:
  api:
    build: .
    container_name: finance_backend
    ports:
      - "5000:5000"
    volumes:
      # Mapeia a pasta local para dentro do container (atualiza o código em tempo real)
      - .:/app
      # Protege a pasta node_modules para não dar conflito com o seu PC
      - /app/node_modules
    env_file:
      - .env
    restart: unless-stopped